module.exports = {
  // Country
  NAME: "NAME",
  CODE: "CODE",
  FLAG: "FLAG",

  // Server
  COUNTRY: "COUNTRY",
  INBOUND: "INBOUND",
  REMARK: "REMARK",
  EDIT_NAME: "EDIT_NAME",
  EDIT_REMARK: "EDIT_REMARK",

  // Plan
  DAYS: "DAYS",
  TRAFFIC: "TRAFFIC",
  PRICE: "PRICE",
  EDIT_NAME: "EDIT_NAME",
  EDIT_DAYS: "EDIT_DAYS",
  EDIT_TRAFFIC: "EDIT_TRAFFIC",
  EDIT_PRICE: "EDIT_PRICE",

  // General
  DESCRIPTION: "DESCRIPTION",
  CONFIRM: "CONFIRM",
};
